### ISSUE TITLE
Can't navigate back when details are expanded

### ISSUE THREAD

**Issue by ciriousjoker** [wiredashio/wiredash-sdk#242] opened 2022-08-04 19:21 UTC
**Describe the bug**

Steps:
- Open feedback
- Navigate to last step
- Navigate back (works)
- Navigate to last step
- Click "show details"
- Navigate back (doesn't work!)
- Click "hide details"
- Navigate back (works again)

**Stacktrace**
N/A

**Wiredash SDK Info**
1.1.0

**Flutter SDK**
3.0.4

**Screenshots**
N/A

**Comment by passsy** [comment] 2022-08-04 19:30
Good catch! I can reproduce it 👍

**Comment by ciriousjoker** [comment] 2023-02-05 15:46
This is still a bug, but now for some reason the behavior changed a little:
- go to last page
- open details
- click "back"
- close details

App now automatically jumps back instead of waiting for the next input.
Looks like some Future in WillPopScope is finished when the user closes the details panel?

Wiredash 1.5.0

**Comment by passsy** [comment] 2023-06-02 09:50
This has been automatically resolved by the recent Flutter updates. I can't reproduce it anymore with Flutter 3.0+

**Closed as completed by passsy** 2023-06-02 09:50 UTC
Labels: bug
