### ISSUE TITLE
Invalid email if it contains a - in domain

### ISSUE THREAD

**Issue by claudecauvet** [wiredashio/wiredash-sdk#95] opened 2020-10-28 12:19 UTC
Hi,

When reporting a feedback, it sounds like an email with a domain containing a minus (-) is not accepted.
For example john.smith@my-corp.com is not allowed.

Best Regards.

Claude

**Comment by brianegan-wiredash** [comment] 2020-11-02 14:56
Oh my, thanks for the report Claude! Sorry about the issue. I'll take a look at the validation and fix it up.

**Comment by claudecauvet** [comment] 2020-11-02 16:59
You don't have to apologize, I'm also familiar with generating bugs ;-)

**Comment by brianegan-wiredash** [comment] 2020-11-06 12:43
Heya @claudecauvet  -- could you please elaborate a bit more on how you ran into this issue, or perhaps the exact email address that was rejected? 

Unfortunately, I couldn't reproduce the issue. I added a test case to our Unit Testing suite on the Flutter side to check for the "john.smith@my-corp.com," but it accepted that email address as valid without any code changes. 

I also checked our server-side code and didn't see any blockers there.

Finally, I was also able to submit a feedback using the "john.smith@my-corp.com" email address as well, and was able to see it in my test console:

<img width="910" alt="Screen Shot 2020-11-06 at 1 38 47 PM" src="https://user-images.githubusercontent.com/72756198/98367380-cd9e6f00-2035-11eb-9dc7-fc3661ba7fd2.png">

Therefore, I think our Validation logic is working, but I'd need a bit more info to investigate!

**Comment by claudecauvet** [comment] 2020-11-06 13:09
Hello !

Thanks for your message.

I've made a new test in my app, and I still have the problem with the fictive email address that I use (john.smith@my-corp.com). Same thing with a real one (which I can't communicate to you, sorry).

![Screenshot_2020-11-06-13-47-24-882](https://user-images.githubusercontent.com/59092344/98369697-a3e74700-2039-11eb-9ff5-709fe98f84b1.jpg)

I don't know if it can have an impact, but my app - and the wiredash plugin - are in French.

BR.

**Comment by brianegan-wiredash** [comment] 2020-11-06 13:26
Thanks for the follow-up information, @claudecauvet!

I've spotted the issue: Another contributor fixed the email validation on September 21st, but we have not deployed a new version with that fix to pub.dev.

I'll publish a new version in the next week and post a note here when I do! :)

**Comment by claudecauvet** [comment] 2020-11-06 15:11
Cool :-)
Have a nice w.e.

**Comment by flschweiger** [comment] 2020-12-22 20:33
This should be fixed by now - let us know if something like this still happens 🙃 

Stay safe and have a great holiday season!

**Closed by flschweiger** 2020-12-22 20:33 UTC
