### ISSUE TITLE
Crash on Web, Backdrop Element Not Found

### ISSUE THREAD

**Issue by rayliverified** [wiredashio/wiredash-sdk#257] opened 2022-10-24 15:47 UTC
**Describe the bug**
Wiredash crashes on Web with a framework issue. Unable to go back to app. 
There seems to be some odd reparenting widget operation with Wiredash perhaps.

![image](https://user-images.githubusercontent.com/19896174/197568805-3fb4a643-ac3c-4713-b1a9-109a0c08f906.png)

**Stacktrace**
```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building WiredashBackdrop(dependencies: [FeedbackModelProvider,
flutter: MediaQuery, _InheritedWiredashTheme], state: _WiredashBackdropState#6137c(tickers: tracking 2
flutter: tickers)):
flutter: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 5334 pos 14:
flutter: '_dependents.isEmpty': is not true.
flutter: 
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=2_bug.md
flutter: 
flutter: The relevant error-causing widget was:
flutter:   Wiredash
flutter:   Wiredash:file:///Users/birjuvachhani/Documents/Projects/Codelessly/codelessly/lib/main.dart:226:14
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #2      InheritedElement.debugDeactivated.<anonymous closure> (package:flutter/src/widgets/framework.dart:5334:14)
flutter: #3      InheritedElement.debugDeactivated (package:flutter/src/widgets/framework.dart:5336:6)
flutter: #4      _InactiveElements._deactivateRecursively.<anonymous closure> (package:flutter/src/widgets/framework.dart:1939:15)
flutter: #5      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1941:6)
flutter: #6      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
flutter: #7      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
flutter: #8      MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6398:16)
flutter: #9      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
flutter: #10     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
flutter: #11     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
flutter: #12     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
flutter: #13     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
flutter: #14     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6398:16)
flutter: #15     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
flutter: #16     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
flutter: #17     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
flutter: #18     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6398:16)
flutter: #19     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
flutter: #20     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
flutter: #21     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
flutter: #22     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
flutter: #23     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1937:13)
```

**Wiredash SDK Info**
v1.5.0 latest
Web

**Flutter SDK**
v3.3.4

**Comment by passsy** [comment] 2022-10-24 18:45
Thanks for reporting the issue. I can't reproduce it with our example. I tested it with `--web-renderer canvaskit` and `--web-renderer html`. Therefore, I have to assume the error is within your app code.

There is a pretty helpful answer on [StackOverflow](https://stackoverflow.com/a/71085742), describing possible mistakes causing this error.
Additionally, I recommend, removing Widgets from your App to quickly exclude parts that are not causing errors.

When opening `Wiredash`, the widget tree is wrapped with additional widgets. Your App Widget will be deactivated and activated while moving it to the new location using a `GlobalKey`. Check your Widgets for the usage of the `activate()` and `deactivate()` functions, there might be a mistake or a missing `super` call. Also, check your `dispose` methods for missing `super` calls.

Please let me know your findings ✌️

**Comment by rayliverified** [comment] 2022-10-24 22:59
Thank you for taking a look Pascal!

There might be some duplicate Global Keys that are not being instantiated correctly. On your end, can you verify that Wiredash works with Navigator 2? 

```
  // Persist the navigator with a global key.
  @override
  GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();
```

I've mentioned to @flschweiger a few of my issues with wrapping the entire app with Wiredash before. It makes me very hesitant to use or recommend Wiredash even though everything else is really good. 

I would like to see more modular functionality and a `Wiredash.instance` pattern over a global wrapper. Would help support many more use cases like capturing a single screen, redacting user privacy data, and contextless invokations of Wiredash to support more architecture patterns. 

Love the NPS feature and dashboard, not so much the global Wiredash wrapper.

**Comment by passsy** [comment] 2022-10-24 23:47
> On your end, can you verify that Wiredash works with Navigator 2?

Absolutely. All my customer apps use Navigator 2, with either go_router or beamer. Especially since `wiredash: 1.0.0` it's not an issue anymore because we removed the previously required `navigatorKey`.

> [wrapping] makes me very hesitant to use or recommend Wiredash even though everything else is really good.

Wiredash doesn't do anything unless it's opened. When closed, the widget doesn't modify anything and [returns](https://github.com/wiredashio/wiredash-sdk/blob/9c2ab8709abc69303a7d46104283709184498345/lib/src/core/wiredash_widget.dart#L226) your app untouched.

Because Wiredash is just a widget, you can place it around every screen. We don't recommend it because you lose the ability to navigate while taking a screenshot. But it works.
For some localization scenarios we also explicitly recommend placing [Wiredash above the navigator](https://docs.wiredash.io/sdk/localization/#access-locale-from-materialapp), not above the `MaterialApp`. 

If you want, you can call Wiredash without `context` (like any other StatefulWidget). There's no need for a Singleton in the SDK.

```dart
final GlobalKey<State<MaterialApp>> _appKey = GlobalKey<State<MaterialApp>>();
WiredashController get wiredashInstance => Wiredash.of(_appKey.currentContext!);

// Access context below Wiredash widget with a global key 
@override
Widget build(BuildContext context) {
  return Wiredash(
    child: MaterialApp(
      key: _appKey,
      //...
    ),
  );
}

return Scaffold(
  floatingActionButton: FloatingActionButton(
    onPressed: () {
      // Access wiredashInstance without context
      wiredashInstance.show();
    },
    child: Icon(Icons.chat),
  ),
);
```

**Comment by passsy** [comment] 2022-11-11 18:06
Closing this, because it is app, not wiredash related.

**Closed as completed by passsy** 2022-11-11 18:06 UTC
Labels: bug
